main: com.github.alexqp.redye.main.Redye
name: ${project.parent.name}
version: ${project.parent.version}
author: alexqp
description: ${project.parent.description}
api-version: "1.17"
website: ${project.parent.url}